spring.application.name=xitlar
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.dbcp2.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

token.secret.key=${JWT_SECRET_KEY}

admin.default.username=${ADMIN_DEFAULT_USERNAME}
admin.default.password=${ADMIN_DEFAULT_PASSWORD}
 
# Swagger / OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=list

# Storage Configuration
app.storage.path=${STORAGE_PATH}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


