spring.application.name=xitlar
spring.datasource.url=jdbc:postgresql://localhost:5432/xitlar
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.dbcp2.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true